POST http://localhost:5247/api/patients/04122098765/bedassignments
Content-Type: application/json

{
  "from": "2026-06-15T09:00:00",
  "to": "2026-06-20T10:00:00",
  "bedType": "Standard",
  "ward": "Kardiologia"
}